[package]
name = 'pallet-ema-oracle'
version = '1.1.3'
description = 'Exponential moving average oracle for AMM pools'
authors = ['GalacticCouncil']
edition = '2021'
license = 'Apache 2.0'
repository = 'https://github.com/galacticcouncil/warehouse'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
serde = {features = ['derive'], optional = true, version = '1.0.136'}
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
codec = { package = 'parity-scale-codec', version = '3.4.0', default-features = false, features = ['derive', "max-encoded-len"] }

# HydraDX dependencies
hydradx-traits = { workspace = true }
hydra-dx-math = { workspace = true }

# Substrate dependencies
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-arithmetic = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }

log = { version = "0.4.14", default-features = false }

[dev-dependencies]
pretty_assertions = "1.3.0"
proptest = "1.0.0"
rug = { version = "1.17.0", features = ["num-traits"] }
sp-io = { workspace = true }

[features]
default = ['std']
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
]
std = [
  'serde',
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'frame-benchmarking/std',
  'log/std',
  'sp-arithmetic/std',
  'sp-core/std',
  'sp-std/std',
  'hydradx-traits/std',
  'hydra-dx-math/std',
  'scale-info/std',
]
try-runtime = ["frame-support/try-runtime"]
