[package]
name = "pallet-staking"
version = "2.1.2"
authors = ['GalacticCouncil']
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/galacticcouncil/hydradx-node'
repository = 'https://github.com/galacticcouncil/hydradx-node'
description = "HydraDX Staking pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# parity
scale-info = { version = "2.3.1", default-features = false, features = ["derive"] }
codec = { default-features = false, features = ["derive"], package = "parity-scale-codec", version = "3.4.0" }
serde = { version = "1.0.136", features = ["derive"], optional = true }
log = { version = "0.4.17", default-features = false }

# ORML
orml-traits = { workspace = true }

hydra-dx-math = { workspace = true }

sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-io = { workspace = true }
sp-core = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
pallet-democracy = { workspace = true }

[dev-dependencies]
pallet-uniques = { workspace = true }
orml-tokens = { workspace = true }
pallet-balances = { workspace = true }
pretty_assertions = "1.2.1"

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"serde",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-core/std",
    "pallet-balances/std",
	"pallet-uniques/std",
	"orml-tokens/std",
	"pallet-democracy/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-uniques/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime",]
