[package]
name = "pallet-xcm-rate-limiter"
version = "0.1.4"
authors = ["GalacticCouncil <hydradx@galacticcouncil.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/galacticcouncil/hydradx-node'
repository = 'https://github.com/galacticcouncil/hydradx-node'
description = "Rate limiter for tokens arriving via XCM"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
serde = { features = ["derive"], optional = true, version = "1.0.136" }
codec = { default-features = false, features = ["derive"], package = "parity-scale-codec", version = "3.4.0" }
scale-info = { version = "2.3.1", default-features = false, features = ["derive"] }

# Hydradx
hydradx-traits = { workspace = true }
hydra-dx-math = { workspace = true }

# Substrate dependencies
frame-benchmarking = { workspace = true, optional = true}
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-core = { workspace = true }

# Polkadot
xcm = { workspace = true }
polkadot-core-primitives = { workspace = true }
polkadot-parachain = { workspace = true }

# Cumulus
cumulus-pallet-xcmp-queue = { workspace = true }

# orml
orml-traits = { workspace = true }

[dev-dependencies]
pallet-balances = { workspace = true, features = ["std"] }
pallet-omnipool = { workspace = true, features = ["std"] }
orml-tokens = { workspace = true, features = ["std"] }
pretty_assertions = "1.2.1"

[features]
default = ['std']
std = [
    'sp-std/std',
    'sp-core/std',
    'sp-runtime/std',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'serde/std',
    'scale-info/std',
    'cumulus-pallet-xcmp-queue/std',
    'orml-traits/std',
    'hydra-dx-math/std',
]
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
]
try-runtime = [ "frame-support/try-runtime" ]
