[package]
name = "test-utils"
version = "1.1.1"
description = "Utility functions for testing pallets"
authors = ["GalacticCouncil"]
edition = "2021"
license = "Apache 2.0"
repository = "https://github.com/galacticcouncil/warehouse"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-system = { workspace = true }

pretty_assertions = { version= "1.3.0", default-features = false, features = ["alloc"] }

[features]
default = ["std"]

std = [
    "frame-system/std",
]
