[package]
name = "pallet-transaction-pause"
version = "1.0.1"
authors = ["Acala Developers", "GalacticCouncil"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
sp-runtime = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-std = { workspace = true }
log = { workspace = true }

# Optionals
frame-benchmarking = { workspace = true, optional = true }
sp-api = { workspace = true, optional = true }

[dev-dependencies]
sp-core = { workspace = true }
sp-io = { workspace = true }
pallet-balances = { workspace = true }
orml-tokens = { workspace = true, features=["std"] }
orml-traits = { workspace = true, features=["std"] }
smallvec = "1.9.0"

[features]
default = ["std"]
std = [
	"scale-info/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"sp-std/std",
	"pallet-balances/std",
]
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
