[package]
name = "pallet-relaychain-info"
version = "0.3.4"
description = "Relaychain info pallet provides various support features for a parachain"
authors = ["GalacticCouncil"]
edition = "2021"
license = "Apache 2.0"
repository = "https://github.com/galacticcouncil/warehouse/tree/master/relaychain-info"

[dependencies]
codec = { default-features = false, features = ["derive"], package = "parity-scale-codec", version = "3.4.0" }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }

# Substrate dependencies
sp-std = { workspace = true }
sp-api = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }

cumulus-primitives-core = { workspace = true }
cumulus-pallet-parachain-system = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "sp-std/std",
    "sp-api/std",
    "cumulus-primitives-core/std",
    "cumulus-pallet-parachain-system/std"
]
try-runtime = ["frame-support/try-runtime"]
